const constants = {
    LOAD_BOOKS: "LOAD_BOOKS",
    IS_LOADING: "IS_LOADING",
    SET_CUSTOM_ERROR: "SET_CUSTOM_ERROR",
    SET_PAGINATION_TOTAL: "SET_PAGINATION_TOTAL",
    SET_PAGINATION_ACTIVE_PAGE: "SET_PAGINATION_ACTIVE_PAGE"
};

export default constants;
